name: 'CI'
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          fetchViaCommits: true
          # configuration: ".github/configuration.json"
          configurationJson: |
            {
              "label_extractor": [
                {
                  "pattern": "(.*)/(.+)",
                  "on_property": "branch",
                  "target": "$1",
                  "flags": "gu"
                }
              ]
            }

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
